- .gitignore
- Makefile
- config/manager/manager.yaml
- controllers/application_controller.go
Note: The functional support for the already deprecated seccomp annotations seccomp.security.alpha.kubernetes.io/pod (for the whole pod) and container.seccomp.security.alpha.kubernetes.io/[name] (for a single container) is going to be removed with the release of Kubernetes v1.25. Please always use the native API fields in favor of the annotations. 
Oppdatert for bruk av den nye metoden for å sette securityContext siden annotation er på vei ut. Fra det jeg så var dette eneste stedet det settes i skiperator
> updated method for setting security-context

- controllers/default_deny_network_policy.go
Pods not starting due to change in network policies, add kasten-io to exclusions while performing PoC. Task added for new network policies for Kasten-io after completion of PoC
> added exclusion for kasten-io in network-policies

- controllers/certificate.go
Changed to a more generic name for certificate clusterissuer. Changed [CA to Buypass](https://kartverket.atlassian.net/browse/SKIP-573).
> Changed name for clusterissuer

- README.md
- api/v1alpha1/application.go
- controllers/deployment.go
- deployment/skiperator.kartverket.no_applications.yaml
Dette skapte masse krøll med eksisterende terraform state som har cachet CRD-en og med at det også endrer på API-et for `path` og `port`. Vi må få opp sandbox-miljøet først og få testet dette ordentlig og laget en migrasjonssti for brukerene
> Revert "Use kubernetes probe definition (#30)"

- controllers/ingress_gateway.go
- controllers/network_policy.go
- controllers/utils.go
This ensures other external patterns are implicitly supported, like `norgeskart.no`. The only DNS wildcard that is currently pointing to the internal ingress is `*.env.skip.statkart.no`.
The only tradeoff is that the implicit behavior makes it possible to expose things by accident, but I see this as unlikely as that would require pointing DNS to the external dns first.
> Flip logic for choosing ingress

- README.md
- controllers/egress_service_entry.go
- tests/access-policy/00-application.yaml
- tests/access-policy/00-assert.yaml
It's currently documented that we support external allowlisting of hosts without specifying port. This was not the case because it created ServiceEntry files with no port, which is not supported.
Not specifying ports now implicitly creates a HTTPS port opening. Does not open HTTP as a nudge towards using HTTPS everywhere, that must be set manually.
> Set default value for external ports

- controllers/default_deny_network_policy.go
Added a nil check on the instanaConfigMap to prevent skiperator from crashing when the CIDR block is not present, for example when testing locally.
> nil check on configmap to prevent crash

- controllers/utils.go
Kubecost blir blokkert av default deny.  
Kan sette den på exclude inntil vi har testet ferdig og kan utrede hvilke nettverksregler som trengs.
> exclude kubecost

- deployment/main.tf
Fixes faulty deploy in develop env due to local skiperator run in the wrong context. See #98 for solution to the underlying problem.
> Forcibly override field manager for clusterrole too

- .github/workflows/dispatch-deploy.yml
Makes the regular deployment workflow sequential instead of parallell. Also creates a new workflow for sequential deployment of a specific image, allowing for quicker rollbacks to old versions, should that be necessary.
> [SKIP-771] Safer deployment

- pkg/util/helperfunctions.go
Excludes crossplane namespace skiperator namespace reconcile for PoC
> Exclude crossplane namespace

- pkg/util/helperfunctions.go
Excludes crossplane namespace skiperator namespace reconcile for PoC
> Add upbound-system exclusion

- api/v1alpha1/application.go
- samples/application.yaml
omitempty being omitted _(hehe)_ caused the namespace field to be populated even though no namespace was present. This forced a diff in ArgoCD and was requested fixed by @esphen
> Omitempty for internalrules

- pkg/util/helperfunctions.go
add instana-autotrace-webhook to list of excluded namespaces so Skiperator won't pick it up
> exclude instana-autotrace-webhook

- go.mod
- go.sum
Previous warning from `go mod tidy`:
```
github.com/kartverket/skiperator imports
go.etcd.io/etcd/server/v3 imports
go.etcd.io/etcd/server/v3/etcdmain imports
go.etcd.io/etcd/server/v3/config imports
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
google.golang.org/grpc/interop imports
golang.org/x/oauth2/google imports
cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
cloud.google.com/go v0.65.0 (/Users/evenholthe/dev/go/pkg/mod/cloud.google.com/go@v0.65.0/compute/metadata)
cloud.google.com/go/compute v1.7.0 (/Users/evenholthe/dev/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata) …
```
> Fix ambiguous import

- controllers/application/configmap.go
- controllers/application/deployment.go
- controllers/application/egress_service_entry.go
- controllers/application/horizontal_pod_autoscaler.go
- controllers/application/ingress_gateway.go
- controllers/application/ingress_virtual_service.go
- controllers/application/network_policy.go
- controllers/application/peer_authentication.go
- controllers/application/service.go
- controllers/application/service_account.go
- pkg/util/constants.go
- tests/minimal/00-assert.yaml
When Argo and Skiperator run in the same system they conflict when tearing down a namespace. This PR tells Argo not to touch skiperator app generated resources so namespaces don't get into an infinite terminating state.
Uses this annotation: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources
Tested in sandbox. Seems to work.
> Stop argo pruning skiperator owned resources

- controllers/application/certificate.go
- controllers/application/controller.go
- controllers/application/deployment.go
- controllers/application/egress_service_entry.go
- controllers/application/horizontal_pod_autoscaler.go
- controllers/application/ingress_gateway.go
- controllers/application/ingress_virtual_service.go
- controllers/application/network_policy.go
- controllers/application/peer_authentication.go
- controllers/application/service.go
- controllers/application/service_account.go
- controllers/namespace/controller.go
- pkg/util/helperfunctions.go
- pkg/util/reconciler.go
Annotations added automatically, in this case `"deployment.kubernetes.io/revision": "7"`, were overwritten by Skiperator, forcing looping reconciles.
Added a helper util for merging the current annotations with the common annotations.
> [SKIP-983] Add common annotation util

- Dockerfile
- go.mod
We're currently using go 1.18. See the release notes for the following versions:
- [1.19](https://tip.golang.org/doc/go1.19)
- [1.20](https://tip.golang.org/doc/go1.20)
My favorite tidbits:
**Runtime**
> On Unix operating systems, Go programs that import package [os](https://tip.golang.org/pkg/os/) now automatically increase the open file limit (RLIMIT_NOFILE) to the maximum allowed value; that is, they change the soft limit to match the hard limit. This corrects artificially low limits set on some systems for compatibility with very old C programs using the [select](https://en.wikipedia.org/wiki/Select_(Unix)) system call. Go programs are not helped by that limit, and instead even simple programs like gofmt often ran out of file descriptors on such systems when processing many files in …
> Bump Go to 1.20

- controllers/application/deployment.go
- tests/minimal/00-assert.yaml
Suggested fix to allow for using [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission) in enforce mode alongside Istio sidecars.
Moves SeccompProfile from container level to pod level so it applies to the istio sidecars as well as the application container, which should make PSA happy.
See: https://github.com/istio/istio/issues/35894
> [SKIP-616] Move SeccompProfile from Container to Pod level

- cmd/skiperator/main.go
Already in use, so it's just and outdated reference
> k8s.io/api/autoscaling: v2beta2 => v2

- README.md
- api/v1alpha1/application.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/skiperator.kartverket.no_applications.yaml
- controllers/application/controller.go
- controllers/application/ingress_virtual_service.go
- pkg/util/helperfunctions.go
- tests/validation-ingresses/00-application.yaml
- tests/validation-ingresses/00-assert.yaml
- tests/validation-ingresses/01-delete-application.yaml
Created a wrapper for Validation Functions and a PoC for how to validate different resources with proper errors. Not sure if this is how we should handle validation long term, but it seems to suffice now.
Ingresses can not be empty, contains spaces or uppercase letters.
Result of a malformed ingress here:
RedirectToHTTPS defaults to true.
> SKIP-1052 Validate Ingresses and Redirect https default true

- cmd/skiperator/main.go
- config/crd/skiperator.kartverket.no_applications.yaml
Metrics are gathered but never exposed.
> Expose Prometheus metrics at :8181

- controllers/application/deployment.go
If typemeta is not defined on deployment struct init, resource labels are not added due to the source object not having its typemeta set before the actual creation of the resource.
This caused gatekeeper to not allow replicalimits to be less than 2 even if the resource label for excluding this rule was added.
> Add typemeta to deployment init

- controllers/application/service.go
When using ServiceMonitors, it creates a selector that selects a service. This currently uses the `app` label, which is not present on the service (in fact there are no labels on it at all). This PR adds labels to the service.
> Add app label to service

- README.md
- api/v1alpha1/podtypes/probe.go
- config/crd/skiperator.kartverket.no_applications.yaml
- controllers/application/deployment.go
Removing a self-imposed limitation.
See the updated [HTTPGetAction in the v1 k8n spec](https://github.com/kubernetes/api/blob/master/core/v1/types.go)
> Allow port number or name in probes

- controllers/application/deployment.go
- tests/service-monitor/04-assert.yaml
This enables referring to port name when enabling prometheus.
```yaml
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
name: my-app
namespace: my-ns
spec:
image: "evenh/prom-demo:latest"
port: 5000
priority: low
additionalPorts:
- name: management
port: 5100
protocol: TCP
liveness:
path: /actuator/health
port: management
prometheus:
path: /actuator/prometheus
port: management # This will now be resolved to an actual port number, used for instructing Istio where to scrape
```
> Istio+Prometheus: Resolve port name to port number

- controllers/application/ingress_virtual_service.go
- tests/ingress/04-application.yaml
- tests/ingress/04-assert.yaml
- tests/ingress/05-delete-application.yaml
When exposing multiple ports and not specified, Istio won't know where to direct the traffic
> Always specify default port for VirtualService

- api/v1alpha1/application_types.go
- api/v1alpha1/podtypes/access_policy.go
- config/crd/skiperator.kartverket.no_applications.yaml
- controllers/application/authorization_policy.go
- controllers/application/controller.go
- controllers/application/deployment.go
- controllers/application/network_policy.go
- controllers/application/peer_authentication.go
- controllers/application/pod_disruption_budget.go
- controllers/application/service.go
- controllers/application/service_monitor.go
- go.mod
- go.sum
- pkg/resourcegenerator/core/pod.go
- pkg/resourcegenerator/istio/peer_authentication.go
- pkg/resourcegenerator/istio/service_entry.go
- pkg/resourcegenerator/networking/network_policy.go
- pkg/util/constants.go
- pkg/util/helperfunctions.go
- pkg/util/reconciler.go
- samples/application.yaml
- tests/minimal/00-assert.yaml
- tests/service-monitor/00-assert.yaml
- tests/service-monitor/02-assert.yaml
- tests/service-monitor/04-assert.yaml
Extracts some functions which generate resources to its own library. Avoids having the future SKIPJob controller fetch from the Application controller package, instead creating a new one. Only done for resources which will be used by SKIPJobs in the future, see #227
Not sure where exactly to put the istio constants and the `IstioEnabled()` function. If there are any inputs as to where this should be placed let me know :)
> [SKIP-705] Extract resource generation to own packages

- controllers/application/deployment.go
When a reconciliation loop adds a new annotation to the map it is silently reused for other apps reconciling at a later time.
This leads to a case where an app who doesn't have a Prometheus block specified gets attempted scraped at the previous reconciled app's (with Prometheus config) port and path.
FYI @christianmosveen 
SKIP-1134
> Fix bug in mutable and shared annotations

- controllers/application/controller.go
Some weird interactions with finalizer currently, not sure why.
Would love to be able to remove the annoying 
```
{"controller": "skipjob", "controllerGroup": "skiperator.kartverket.no", "controllerKind": "SKIPJob", "SKIPJob": {"name":"condition-finish","namespace":"test"}, "namespace": "test", "name": "condition-finish", "reconcileID": "49b70cf2-d983-46be-b125-c8ae25b449e9", "error": "Operation cannot be fulfilled on skipjobs.skiperator.kartverket.no \"condition-finish\": StorageError: invalid object, Code: 4, Key: /registry/skiperator.kartverket.no/skipjobs/test/condition-finish, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 23dff9d9-88ab-45e9-8a2f-798562f4960b, UID in object meta: "}
```
error was well, but not sure why it's happening. something …
> Fix wordy "could not init status" error message on Application init

- api/v1alpha1/application_types.go
- controllers/application/controller.go
- controllers/application/deployment.go
- tests/application/resource-label/00-application.yaml
- tests/application/resource-label/00-assert.yaml
- tests/config.yaml
Labels field in application definition now propegate correctly to pod template in deployment.
Changes GroupKindFromControllerResource to a map instead of a function as it was essentially already functioning as one.
Uses the standard SetResourceLabelIfApplies by adding Pod to the ControllerResources and adding a map from the resource -> GroupKind.
Had to create a pod and extract the template, as PodTemplateSpec does not implement type Object, which is needed for setting labels.
> Added labels to deployment pod template spec

- api/v1alpha1/skipjob_defaults.go
It was not a bug, but rather the result of some poor programming on my end.
Both the source and destination for mergo referred to the same cron struct, so updating the source struct caused the destination to be updated as well, regardless of what mergo did :)
> Fix mergo 'bug'

- controllers/application/authorization_policy.go
- controllers/application/certificate.go
- controllers/application/configmap.go
- controllers/application/controller.go
- controllers/application/deployment.go
- controllers/application/egress_service_entry.go
- controllers/application/horizontal_pod_autoscaler.go
- controllers/application/ingress_gateway.go
- controllers/application/ingress_virtual_service.go
- controllers/application/network_policy.go
- controllers/application/peer_authentication.go
- controllers/application/pod_disruption_budget.go
- controllers/application/service.go
- controllers/application/service_account.go
- controllers/application/service_monitor.go
- pkg/resourcegenerator/istio/service_entry.go
- pkg/util/reconciler.go
- tests/application/ignore-reconcile/00-application.yaml
- tests/application/ignore-reconcile/00-assert.yaml
- tests/application/ignore-reconcile/01-assert.yaml
- tests/application/ignore-reconcile/01-virtualservice-set-label.yaml
- tests/application/ignore-reconcile/02-application-change-ingress.yaml
- tests/application/ignore-reconcile/02-assert.yaml
- tests/application/ignore-reconcile/02-errors.yaml
- tests/application/ignore-reconcile/03-assert.yaml
- tests/application/ignore-reconcile/03-virtualservice-remove-label.yaml
- tests/application/ignore-reconcile/04-delete-application.yaml
In some cases it may be necessary to manually edit child resources of an application. This is usually in the short term in terms of debugging a problem or when implementing a temporary workaround. In this case we need the latter and instead of migrating the team out of their skiperator app we add a feature here to allow us to edit the Gateway resource temporarily.
This PR adds a feature where you can manually label a child with `skiperator.kartverket.no/ignore: "true"` to opt that resource out of reconciliation. When you are done with that resource, you simply remove the label. Note that this is not something you can do via `resourceLabels`, as skiperator will add the label but because of the resource then being opted out of reconcile it will not remove the label.
I forsee this feature as …
> Add support for ignoring reconciliation of children

- api/v1alpha1/skipjob_types.go
- config/crd/skiperator.kartverket.no_skipjobs.yaml
Updating the container settings for Cron jobs makes sense, as a product team might want to change the behaviour of a job between runs (for example an updated image). It is still not allowed to update the container settings for a one-off job.
> Allow updating container for cron jobs

- controllers/skipjob/job.go
- pkg/resourcegenerator/core/pod.go
After allowing editing of `spec.container` if `spec.cron` was set, it seems we allowed a lurking bug which updated the SKIPJob spec with the GCP env for every reconcile loop, and updating the spec caused another reconcile loop which again added a new GCP env to the spec.
With this change it is never added to the spec of the SKIPJob, a copy is used instead.
> Do not add gcp env var to skipjob spec, make copy instead

- controllers/application/pod_disruption_budget.go
Enabled i kubernetes 1.27, but supported in 1.26 spec.
From the kubernetes docs:
> It is recommended to set AlwaysAllow [Unhealthy Pod Eviction Policy](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy) to your PodDisruptionBudgets to support eviction of misbehaving applications during a node drain. The default behavior is to wait for the application pods to become [healthy](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#healthiness-of-a-pod) before the drain can proceed.
> Set UnhealthyPodEviction to AlwaysAllow

- controllers/application/deployment.go
- tests/application/resources-modification/00-application.yaml
- tests/application/resources-modification/00-assert.yaml
- tests/application/resources-modification/01-application.yaml
- tests/application/resources-modification/02-assert.yaml
- tests/application/resources-modification/03-delete-application.yaml
Should be rolled out slowly (e.g. sandbox first) in order to verify that we're not introducing another reconciliation loop.
See SKIP-1245.
> Fix "resources" not getting updated

- pkg/resourcegenerator/core/pod.go
- tests/application/minimal/application-assert.yaml
The Caddy dockerfile sets the net_bind_service capability, so even if we don't really require it for our usecase, the docker image requires it to run. Without it many frontends will not work.
> Add more permissions for proxy, so frontends can run

- api/v1alpha1/application_types.go
- config/crd/skiperator.kartverket.no_applications.yaml
- controllers/application/controller.go
- controllers/application/deployment.go
- pkg/util/helperfunctions.go
- tests/application/team-label/application-assert.yaml
- tests/application/team-label/application-no-team-assert.yaml
- tests/application/team-label/application-no-team-error-assert.yaml
- tests/application/team-label/application-no-team.yaml
- tests/application/team-label/application-with-fixed-team-assert.yaml
- tests/application/team-label/application-with-fixed-team.yaml
- tests/application/team-label/application.yaml
- tests/application/team-label/chainsaw-test.yaml
- tests/application/team-label/namespace-no-team.yaml
- tests/application/team-label/namespace.yaml
In order to propagate team name down to running Pod's this field needs to be explicitly set or inferred from the Application's namespace.
> application: add 'team' to spec

- api/v1alpha1/podtypes/access_policy.go
- controllers/skipjob/network_policy.go
- tests/skipjob/access-policy-job/skipjob-assert.yaml
Uses the correct labelSelector for SKIPJobs, as the Pods are labeled with `app: nameOfSKIPJob-skipjob`.
Also adds a little line regarding accessPolicy names for SKIPJobs
> Use correct labelselector for skipjob pods in netpol

- controllers/application/deployment.go
- tests/application/minimal/application-assert.yaml
Due to issues with downscaling by cluster-autoscaler we're annotating pods with lenient evict rule to try to combat this.
Tests passed locally.
> added annotation for pod template

- api/v1alpha1/podtypes/pod_settings.go
- cmd/skiperator/main.go
- config/crd/skiperator.kartverket.no_applications.yaml
- config/crd/skiperator.kartverket.no_skipjobs.yaml
- pkg/flags/flags.go
- pkg/resourcegenerator/core/constants.go
- pkg/resourcegenerator/core/pod.go
- pkg/util/reconciler.go
- tests/application/minimal/application-assert.yaml
This is an implementation of anti-affinity rules based on hostname and VMware ESXi host labels (if present). It's currently implemented using [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) but can be switched to using regular (anti-)affinity rules.
> Introduce anti-affinity

- pkg/resourcegenerator/core/pod.go
- tests/application/cloudsql-auth-proxy/application-assert.yaml
PSA: Restricted stops the pod from working without this
> Fix missing security context for cloudsql proxy

- api/v1alpha1/skipjob_types.go
- config/crd/skiperator.kartverket.no_skipjobs.yaml
- internal/controllers/application.go
- internal/controllers/common/util.go
- internal/controllers/common/util_test.go
- internal/controllers/skipjob.go
- pkg/util/helperfunctions.go
When we updated from the crd with the old status object to the new one we ran into a problem where status would be set to `status: {}`. On some applications this would cause an issue where skiperator couldn't update the application since it was an invalid object (missing status). To solve this we need to make sure status is set to the default pending value before we can update the spec.
I wasn't able to reproduce this issue with kind. 
Alternative solutions: 
- set default status with kubebuilder/CRD
- instead of diffing status, check if status == nil
> Missing status when updating to new CRD blocks resource update

- internal/controllers/application.go
- internal/controllers/skipjob.go
- tests/application/access-policy/advanced-error.yaml
- tests/application/access-policy/chainsaw-test.yaml
- tests/skipjob/access-policy-job/chainsaw-test.yaml
- tests/skipjob/access-policy-job/skipjob-assert.yaml
- tests/skipjob/access-policy-job/skipjob-cron-error.yaml
- tests/skipjob/access-policy-job/skipjob-error.yaml
Instead of updating the spec by setting it in the default spec function we just set the ports internally, with no change to the kubernetes resource.
> fix: Autosync loop because we update access policy with ports
